version: '3'
services:
    mongodb:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - 4001:27017
    nginx:
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        restart: always
        ports:
            - '4000:80'
        depends_on:
            - api
            - client
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./api
        volumes:
            - /app/node_modules
            - ./api:/app
        environment:
            MONGODB_ADMINUSERNAME: root
            MONGODB_ADMINPASSWORD: example
            MONGODB_SERVER: mongodb
        depends_on:
            - mongodb
